#发布系统配置
#服务配置,服务维度,以及实例的配置
services-config:
  serviceList:
    - serviceName: sms-service
      unregisterUri: /actuator/unregister
      autoTestUri: /actuator/autoTest
      dockerRunOpt:
        name: '{serviceName}'
        volume: '/data/docker/log/{serviceName}:/data/deploy/log/{serviceName}'
        ultraOpts:
          - env 'JAVA_OPTS=-Xms1024m -Xmx1024m -Dspring.profiles.active=default -Denv=DEV'
          - network host
          - cpu-period=1000000
          - cpu-quota=1000000
      replicaList:
        - ip: 192.168.0.1
          httpPort: 9050
        # - ip: 192.168.100.94
        #   httpPort: 9050
    - serviceName: jobexecutor-service
      unregisterUri: /actuator/unregister
      autoTestUri: /actuator/autoTest
      dockerRunOpt:
        name: '{serviceName}'
        volume: '/data/docker/log/{serviceName}:/data/deploy/log/{serviceName}'
        ultraOpts:
          - network host
          - cpu-period=1000000
          - cpu-quota=1000000
      replicaList:
        - ip: 192.168.0.2
          httpPort: 8011
          ultraOpts:
            - env 'JAVA_OPTS=-Xms512m -Xmx512m -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintGCDetails -Dspring.profiles.active=test'
            - env 'EXECUTOR_NAME=erc-jobexecutor-service'
        - ip: 192.168.0.3
          httpPort: 8011
          ultraOpts:
            - env 'JAVA_OPTS=-Xms512m -Xmx512m -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintGCDetails -Dspring.profiles.active=test'
            - env 'EXECUTOR_NAME=jobexecutor-service'

#服务器节点配置, 登录服务器的方式,密码等配置
server-node-config:
  nodeList:
    - ip: 192.168.0.1
      sshPort: 22
      authType: pubkey
      account: root
      password: thisispassword
      keyPath: /Users/pan/id_rsa
    - ip: 192.168.0.2
      sshPort: 22
      authType: pubkey
      account: root
      password: thisispassword
      keyPath: /Users/pan/id_rsa
    - ip: 192.168.0.3
      sshPort: 22
      authType: pubkey
      account: root
      password: thisispassword
      keyPath: /Users/pan/id_rsa


#qa环境的服务配置，目前主要是用来探测服务的启动状况
services-config-qa:
  serviceList:
    - serviceName: sms-service
      replicaList:
        - ip: 192.168.0.1
          httpPort: 9050
    - serviceName: jobexecutor-service
      replicaList:
        - ip: 192.168.0.2
          httpPort: 9090


#############################################################

#数据库配置
spring.datasource:
  name: datasource
  type: com.alibaba.druid.pool.DruidDataSource
  #druid相关配置
  druid:
    zzc-master:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://192.168.0.1:3306/sentry?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useServerPrepStmts=true&useSSL=true
      username: root
      password: root
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      #spring.cloud.stream.kafka.binder.brokers=secure.server:9092
    zzc-slave:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://192.168.0.1:3306/sentry?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useServerPrepStmts=true&useSSL=true
      username: root
      password: root
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20


spring:
  redis:
    cluster:
      nodes:  192.168.0.1:7000
    password: password707172